language: php

dist: trusty
sudo: false

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION='^3.4'
    - php: 7.1
      env: SYMFONY_VERSION='^4.3'
    - php: 7.2
      env: SYMFONY_VERSION='^3.4'
    - php: 7.2
      env: SYMFONY_VERSION='^4.3'
    - php: 7.3
      env: SYMFONY_VERSION='^3.4'
    - php: 7.3
      env: SYMFONY_VERSION='^4.3'
  fast_finish: true

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit